export const PPODUCTS_REQUEST = 'PPODUCTS_REQUEST'
export const PRODUCTS_FAIL = 'PRODUCTS_FAIL'
export const PRODUCTS_SUCCESS = 'PRODUCTS_SUCCESS'

export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_FAIL  = 'PRODUCT_DETAILS_FAIL'

export const PRODUCT_QUANTITY = 'PRODUCT_QUANTITY'

export const ADD_TO_CART = 'ADD_TO_CART'

export const SAVE_SHIPPING = 'SAVE_SHIPPING'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const EMPTY_CART = 'EMPTY_CART'

export const SIGN_IN_REQUEST = 'SIGN_IN_REQUEST'
export const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS'
export const SIGN_IN_FAIL = 'SIGN_IN_FAIL'
export const SIGN_OUT = 'SIGN_OUT'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const ADD_PRODUCT_REQUEST = 'ADD_PRODUCT_REQUEST'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL'

export const PRODUCT_SAVE_REQUEST = 'PRODUCT_SAVE_REQUEST'
export const PRODUCT_SAVE_SUCCESS = 'PRODUCT_SAVE_SUCCESS'
export const PRODUCT_SAVE_FAIL = 'PRODUCT_SAVE_FAIL'

export const PRODUCT_DELETE_REQUEST = 'PRODUCT_DELETE_REQUEST'
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS'
export const PRODUCT_DELETE_FAIL = 'PRODUCT_DELETE_FAIL'

export const PAYMENT_SUCCESS = 'PAYMENT_SUCCESS'


